services:
  postgres_MARIP_RAMADHAN:
    image: postgres:15
    container_name: postgres_MARIP_RAMADHAN
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - utsnet

  pgadmin_MARIP_RAMADHAN:
    image: dpage/pgadmin4:8
    container_name: pgadmin_MARIP_RAMADHAN
    restart: unless-stopped
    depends_on:
      - postgres_MARIP_RAMADHAN
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"    
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - utsnet

networks:
  utsnet:

volumes:
  pgdata:
  pgadmin:
