DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'backend_dev') THEN
    CREATE ROLE backend_dev LOGIN PASSWORD 'backend_dev_pwd';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bi_dev') THEN
    CREATE ROLE bi_dev LOGIN PASSWORD 'bi_dev_pwd';
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'data_engineer') THEN
    CREATE ROLE data_engineer LOGIN PASSWORD 'data_engineer_pwd';
  END IF;
END$$;

ALTER SCHEMA SALAM OWNER TO postgres;

GRANT USAGE ON SCHEMA SALAM TO backend_dev, bi_dev, data_engineer;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO backend_dev;

GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT SELECT ON TABLES TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT SELECT ON SEQUENCES TO bi_dev;

GRANT CREATE ON SCHEMA SALAM TO data_engineer;
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA SALAM TO data_engineer;

ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON TABLES TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT USAGE, SELECT ON SEQUENCES TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
  GRANT ALL PRIVILEGES ON FUNCTIONS TO data_engineer;
